### ISSUE TITLE
Cannot see in HA

### ISSUE THREAD

**Issue by kszere** [dlsniper/hass-obs#1]
I use Mosquitto broker MQTT.
Auto detection not woks.

I try add to configuration.yaml:
``` yaml
mqtt:
  sensor:
    - name: "OBS Wyse"
      state_topic: "ha_wyse/state"
      icon: "mdi:video-wireless"
      force_update: true
      qos: 1
      payload_available: "online"
      payload_not_available: "offline"
      json_attributes_topic: "ha_wyse/attributes"
```
... and I still can't see.

Can any peaople help me?
I need controol switch scenes for display tv ads.
